export const orders = [
    {
        id: '1',
        customerName: 'Nick Adams',
        location: '123 Main St, Springfield',
        orderDescription: 'Apples, Orange Juice',
        deliveryTime: '2:00 PM',
        price: '₹15.00',
        paymentStatus: 'COD',
        deliveryDate: '01/11/2024',
    },
    {
        id: '2',
        customerName: 'Anthony Adverse',
        location: '456 Elm St, Springfield',
        orderDescription: 'Bread, Milk',
        deliveryTime: '3:30 PM',
        price: '₹12.50',
        paymentStatus: 'UPI',
        deliveryDate: '01/11/2024',
    },
    {
        id: '3',
        customerName: 'Sarah Johnson',
        location: '789 Maple St, Springfield',
        orderDescription: 'Eggs, Flour, Sugar',
        deliveryTime: '4:00 PM',
        price: '₹20.00',
        paymentStatus: 'COD',
        deliveryDate: '01/11/2024',
    },
    {
        id: '4',
        customerName: 'Michael Brown',
        location: '101 Oak St, Springfield',
        orderDescription: 'Chicken, Rice, Vegetables',
        deliveryTime: '5:15 PM',
        price: '₹30.75',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
    },
    {
        id: '5',
        customerName: 'Emily White',
        location: '202 Pine St, Springfield',
        orderDescription: 'Pasta, Tomato Sauce',
        deliveryTime: '6:45 PM',
        price: '₹18.50',
        paymentStatus: 'COD',
        deliveryDate: '02/11/2024',
    },
    {
        id: '6',
        customerName: 'Jessica Smith',
        location: '303 Cedar St, Springfield',
        orderDescription: 'Rice, Lentils',
        deliveryTime: '7:30 PM',
        price: '₹22.00',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
    },
    {
        id: '7',
        customerName: 'Robert Johnson',
        location: '404 Birch St, Springfield',
        orderDescription: 'Beef, Broccoli',
        deliveryTime: '8:00 PM',
        price: '₹35.00',
        paymentStatus: 'COD',
        deliveryDate: '03/11/2024',
    },
    {
        id: '8',
        customerName: 'Linda Davis',
        location: '505 Spruce St, Springfield',
        orderDescription: 'Fish, Chips',
        deliveryTime: '9:15 PM',
        price: '₹40.50',
        paymentStatus: 'UPI',
        deliveryDate: '03/11/2024',
    },
    {
        id: '9',
        customerName: 'Charles Miller',
        location: '606 Ash St, Springfield',
        orderDescription: 'Tacos, Salsa',
        deliveryTime: '10:00 PM',
        price: '₹28.75',
        paymentStatus: 'COD',
        deliveryDate: '03/11/2024',
    },
    {
        id: '10',
        customerName: 'Laura Garcia',
        location: '707 Walnut St, Springfield',
        orderDescription: 'Salad, Dressing',
        deliveryTime: '11:30 AM',
        price: '₹10.00',
        paymentStatus: 'UPI',
        deliveryDate: '04/11/2024',
    },
    {
        id: '11',
        customerName: 'James Wilson',
        location: '808 Cherry St, Springfield',
        orderDescription: 'Cookies, Milk',
        deliveryTime: '12:15 PM',
        price: '₹5.50',
        paymentStatus: 'COD',
        deliveryDate: '04/11/2024',
    },
    {
        id: '12',
        customerName: 'Patricia Martinez',
        location: '909 Peach St, Springfield',
        orderDescription: 'Chocolate Cake',
        deliveryTime: '1:00 PM',
        price: '₹35.00',
        paymentStatus: 'UPI',
        deliveryDate: '05/11/2024',
    },
    {
        id: '13',
        customerName: 'Michael Thompson',
        location: '1010 Lemon St, Springfield',
        orderDescription: 'Pizza, Garlic Bread',
        deliveryTime: '2:30 PM',
        price: '45.00',
        paymentStatus: 'COD',
        deliveryDate: '05/11/2024',
    },
    {
        id: '14',
        customerName: 'Jennifer White',
        location: '1111 Apricot St, Springfield',
        orderDescription: 'Sushi, Soy Sauce',
        deliveryTime: '3:45 PM',
        price: '₹50.00',
        paymentStatus: 'UPI',
        deliveryDate: '06/11/2024',
    },
    {
        id: '15',
        customerName: 'William Harris',
        location: '1212 Plum St, Springfield',
        orderDescription: 'Burger, Fries',
        deliveryTime: '5:00 PM',
        price: '₹25.00',
        paymentStatus: 'COD',
        deliveryDate: '06/11/2024',
    },
    {
        id: '16',
        customerName: 'Susan Clark',
        location: '1313 Fig St, Springfield',
        orderDescription: 'Spaghetti, Meatballs',
        deliveryTime: '6:30 PM',
        price: '₹30.00',
        paymentStatus: 'UPI',
        deliveryDate: '07/11/2024',
    },
    {
        id: '17',
        customerName: 'David Lewis',
        location: '1414 Date St, Springfield',
        orderDescription: 'Chicken Wings',
        deliveryTime: '7:45 PM',
        price: '₹22.50',
        paymentStatus: 'COD',
        deliveryDate: '08/11/2024',
    },
    {
        id: '18',
        customerName: 'Barbara Young',
        location: '1515 Kiwi St, Springfield',
        orderDescription: 'Pancakes, Syrup',
        deliveryTime: '8:30 AM',
        price: '₹15.00',
        paymentStatus: 'UPI',
        deliveryDate: '08/11/2024',
    },
    {
        id: '19',
        customerName: 'Joseph Walker',
        location: '1616 Coconut St, Springfield',
        orderDescription: 'Steak, Potatoes',
        deliveryTime: '9:30 PM',
        price: '₹75.00',
        paymentStatus: 'COD',
        deliveryDate: '09/11/2024',
    },
    {
        id: '20',
        customerName: 'Margaret Hall',
        location: '1717 Olive St, Springfield',
        orderDescription: 'Vegetable Stir Fry',
        deliveryTime: '10:30 AM',
        price: '₹20.00',
        paymentStatus: 'UPI',
        deliveryDate: '10/11/2024',
    },
]