export const orders = [
    {
        id: '1',
        customerName: 'Customer 1',
        location: '996 Random St, Springfield',
        orderDescription: [
            { product: 'Pasta', quantity: 2 },
            { product: 'Tomato Sauce', quantity: 1 },
            { product: 'Cheese', quantity: 1 },
            { product: 'Garlic Bread', quantity: 2 },
        ],
        deliveryTime: '1:15 PM',
        price: '₹49.33',
        paymentStatus: 'COD',
        deliveryDate: '02/11/2024',
        status: 'Delivered',
    },
    {
        id: '2',
        customerName: 'Customer 2',
        location: '983 Random St, Springfield',
        orderDescription: [
            { product: 'Pasta', quantity: 3 },
            { product: 'Tomato Sauce', quantity: 2 },
            { product: 'Basil', quantity: 1 },
            { product: 'Olive Oil', quantity: 1 },
            { product: 'Parmesan', quantity: 1 },
        ],
        deliveryTime: '2:30 PM',
        price: '₹40.98',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'Pending',
    },
    {
        id: '3',
        customerName: 'Customer 3',
        location: '706 Random St, Springfield',
        orderDescription: [
            { product: 'Apples', quantity: 6 },
            { product: 'Orange Juice', quantity: 1 },
            { product: 'Bananas', quantity: 5 },
        ],
        deliveryTime: '4:15 PM',
        price: '₹20.77',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'Delivered',
    },
    {
        id: '4',
        customerName: 'Customer 4',
        location: '389 Random St, Springfield',
        orderDescription: [
            { product: 'Chicken', quantity: 1 },
            { product: 'Rice', quantity: 2 },
            { product: 'Vegetables', quantity: 3 },
            { product: 'Spices', quantity: 1 },
        ],
        deliveryTime: '7:00 PM',
        price: '₹36.29',
        paymentStatus: 'COD',
        deliveryDate: '02/11/2024',
        status: 'Pending',
    },
    {
        id: '5',
        customerName: 'Customer 5',
        location: '822 Random St, Springfield',
        orderDescription: [
            { product: 'Eggs', quantity: 12 },
            { product: 'Flour', quantity: 1 },
            { product: 'Sugar', quantity: 1 },
            { product: 'Milk', quantity: 1 },
            { product: 'Butter', quantity: 1 },
        ],
        deliveryTime: '7:15 PM',
        price: '₹12.74',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'Delivered',
    },
    {
        id: '6',
        customerName: 'Customer 6',
        location: '178 Random St, Springfield',
        orderDescription: [
            { product: 'Chicken', quantity: 1 },
            { product: 'Rice', quantity: 1 },
            { product: 'Vegetables', quantity: 2 },
        ],
        deliveryTime: '2:45 PM',
        price: '₹23.62',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'Pending',
    },
    {
        id: '7',
        customerName: 'Customer 7',
        location: '541 Random St, Springfield',
        orderDescription: [
            { product: 'Chicken', quantity: 2 },
            { product: 'Rice', quantity: 1 },
            { product: 'Vegetables', quantity: 4 },
            { product: 'Sauce', quantity: 1 },
        ],
        deliveryTime: '5:00 PM',
        price: '₹45.77',
        paymentStatus: 'COD',
        deliveryDate: '02/11/2024',
        status: 'Delivered',
    },
    {
        id: '8',
        customerName: 'Customer 8',
        location: '134 Random St, Springfield',
        orderDescription: [
            { product: 'Chicken', quantity: 1 },
            { product: 'Rice', quantity: 3 },
            { product: 'Vegetables', quantity: 2 },
            { product: 'Spices', quantity: 1 },
            { product: 'Chili Sauce', quantity: 1 },
        ],
        deliveryTime: '7:45 PM',
        price: '₹47.36',
        paymentStatus: 'COD',
        deliveryDate: '02/11/2024',
        status: 'Pending',
    },
    {
        id: '9',
        customerName: 'Customer 9',
        location: '440 Random St, Springfield',
        orderDescription: [
            { product: 'Eggs', quantity: 10 },
            { product: 'Flour', quantity: 2 },
            { product: 'Sugar', quantity: 1 },
            { product: 'Baking Powder', quantity: 1 },
        ],
        deliveryTime: '3:00 PM',
        price: '₹37.01',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'Delivered',
    },
    {
        id: '10',
        customerName: 'Customer 10',
        location: '176 Random St, Springfield',
        orderDescription: [
            { product: 'Pasta', quantity: 1 },
            { product: 'Tomato Sauce', quantity: 1 },
            { product: 'Cheese', quantity: 2 },
            { product: 'Basil', quantity: 1 },
        ],
        deliveryTime: '5:00 PM',
        price: '₹14.47',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'Pending',
    },
];