export const orders = [
    {
        id: '1',
        customerName: 'Customer 1',
        location: '996 Random St, Springfield',
        orderDescription: 'Pasta, Tomato Sauce',
        deliveryTime: '1:15 PM',
        price: '₹49.33',
        paymentStatus: 'COD',
        deliveryDate: '02/11/2024',
        status: 'delivered',
    },
    {
        id: '2',
        customerName: 'Customer 2',
        location: '983 Random St, Springfield',
        orderDescription: 'Pasta, Tomato Sauce',
        deliveryTime: '2:30 PM',
        price: '₹40.98',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'pending',
    },
    {
        id: '3',
        customerName: 'Customer 3',
        location: '706 Random St, Springfield',
        orderDescription: 'Apples, Orange Juice',
        deliveryTime: '4:15 PM',
        price: '₹20.77',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'delivered',
    },
    {
        id: '4',
        customerName: 'Customer 4',
        location: '389 Random St, Springfield',
        orderDescription: 'Chicken, Rice, Vegetables',
        deliveryTime: '7:00 PM',
        price: '₹36.29',
        paymentStatus: 'COD',
        deliveryDate: '02/11/2024',
        status: 'pending',
    },
    {
        id: '5',
        customerName: 'Customer 5',
        location: '822 Random St, Springfield',
        orderDescription: 'Eggs, Flour, Sugar',
        deliveryTime: '7:15 PM',
        price: '₹12.74',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'delivered',
    },
    {
        id: '6',
        customerName: 'Customer 6',
        location: '178 Random St, Springfield',
        orderDescription: 'Chicken, Rice, Vegetables',
        deliveryTime: '2:45 PM',
        price: '₹23.62',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'pending',
    },
    {
        id: '7',
        customerName: 'Customer 7',
        location: '541 Random St, Springfield',
        orderDescription: 'Chicken, Rice, Vegetables',
        deliveryTime: '5:00 PM',
        price: '₹45.77',
        paymentStatus: 'COD',
        deliveryDate: '02/11/2024',
        status: 'delivered',
    },
    {
        id: '8',
        customerName: 'Customer 8',
        location: '134 Random St, Springfield',
        orderDescription: 'Chicken, Rice, Vegetables',
        deliveryTime: '7:45 PM',
        price: '₹47.36',
        paymentStatus: 'COD',
        deliveryDate: '02/11/2024',
        status: 'pending',
    },
    {
        id: '9',
        customerName: 'Customer 9',
        location: '440 Random St, Springfield',
        orderDescription: 'Eggs, Flour, Sugar',
        deliveryTime: '3:00 PM',
        price: '₹37.01',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'delivered',
    },
    {
        id: '10',
        customerName: 'Customer 10',
        location: '176 Random St, Springfield',
        orderDescription: 'Pasta, Tomato Sauce',
        deliveryTime: '5:00 PM',
        price: '₹14.47',
        paymentStatus: 'UPI',
        deliveryDate: '02/11/2024',
        status: 'pending',
    },
];