const tasks = [
    {
        id: 1,
        title: "Deliver Groceries",
        description: "Deliver groceries to Anil Kumar at 15 MG Road.",
        assignedDate: "2025-01-03",
        dueTime: "10:30 AM",
        status: "Pending",
        location: {
            address: "15 MG Road, Bengaluru, Karnataka",
            coordinates: { latitude: 12.9716, longitude: 77.5946 },
        },
        customerContact: "9876543210",
    },
    {
        id: 2,
        title: "Pick Up Laundry",
        description: "Pick up laundry from Priya Sharma at 22 Lajpat Nagar.",
        assignedDate: "2025-01-03",
        dueTime: "11:00 AM",
        status: "In Progress",
        location: {
            address: "22 Lajpat Nagar, New Delhi",
            coordinates: { latitude: 28.5672, longitude: 77.2273 },
        },
        customerContact: "8765432190",
    },
    {
        id: 3,
        title: "Deliver Medicine",
        description: "Deliver prescribed medicine to Rajesh Verma at 8 Sector 45.",
        assignedDate: "2025-01-03",
        dueTime: "12:00 PM",
        status: "Completed",
        location: {
            address: "8 Sector 45, Gurugram, Haryana",
            coordinates: { latitude: 28.4595, longitude: 77.0266 },
        },
        customerContact: "7654321098",
    },
    {
        id: 4,
        title: "Pick Up Parcel",
        description: "Pick up a parcel from Kavita Iyer at 19 Nungambakkam.",
        assignedDate: "2025-01-03",
        dueTime: "1:30 PM",
        status: "Pending",
        location: {
            address: "19 Nungambakkam, Chennai, Tamil Nadu",
            coordinates: { latitude: 13.0604, longitude: 80.2496 },
        },
        customerContact: "6543210987",
    },
    {
        id: 5,
        title: "Deliver Documents",
        description: "Deliver legal documents to Arjun Singh at 45 Civil Lines.",
        assignedDate: "2025-01-03",
        dueTime: "3:00 PM",
        status: "In Progress",
        location: {
            address: "45 Civil Lines, Jaipur, Rajasthan",
            coordinates: { latitude: 26.9124, longitude: 75.7873 },
        },
        customerContact: "5432109876",
    },
    {
        id: 6,
        title: "Deliver Cake",
        description: "Deliver birthday cake to Meena Joshi at 33 FC Road.",
        assignedDate: "2025-01-03",
        dueTime: "4:00 PM",
        status: "Pending",
        location: {
            address: "33 FC Road, Pune, Maharashtra",
            coordinates: { latitude: 18.5204, longitude: 73.8567 },
        },
        customerContact: "4321098765",
    },
    {
        id: 7,
        title: "Pick Up Vegetables",
        description: "Pick up fresh vegetables from Shalini Agarwal at 29 Salt Lake.",
        assignedDate: "2025-01-03",
        dueTime: "5:30 PM",
        status: "Completed",
        location: {
            address: "29 Salt Lake, Kolkata, West Bengal",
            coordinates: { latitude: 22.5726, longitude: 88.3639 },
        },
        customerContact: "3210987654",
    },
    {
        id: 8,
        title: "Deliver Clothes",
        description: "Deliver clothes to Ramesh Patel at 55 Paldi.",
        assignedDate: "2025-01-03",
        dueTime: "6:00 PM",
        status: "Pending",
        location: {
            address: "55 Paldi, Ahmedabad, Gujarat",
            coordinates: { latitude: 23.0225, longitude: 72.5714 },
        },
        customerContact: "2109876543",
    },
    {
        id: 9,
        title: "Deliver Package",
        description: "Deliver package to Sunita Nair at 18 Marine Drive.",
        assignedDate: "2025-01-03",
        dueTime: "7:00 PM",
        status: "In Progress",
        location: {
            address: "18 Marine Drive, Mumbai, Maharashtra",
            coordinates: { latitude: 19.0760, longitude: 72.8777 },
        },
        customerContact: "1098765432",
    },
    {
        id: 10,
        title: "Pick Up Books",
        description: "Pick up books from Vijay Gupta at 12 Hazratganj.",
        assignedDate: "2025-01-03",
        dueTime: "8:00 PM",
        status: "Completed",
        location: {
            address: "12 Hazratganj, Lucknow, Uttar Pradesh",
            coordinates: { latitude: 26.8467, longitude: 80.9462 },
        },
        customerContact: "0987654321",
    },
];